### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by wss1942** [abersheeran/websocks#3]
```
[2020-01-11 11:57:07] [INFO] Socks5 Server serving on ('0.0.0.0', 9999)
[2020-01-11 11:57:07] [ERROR] Task exception was never retrieved
future: <Task finished coro=<Pool.init() done, defined at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocks/client.py:48> exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocks/client.py", line 49, in init
    await asyncio.gather(*[self._create() for _ in range(size)])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocks/client.py", line 91, in _create
    self.server, extra_headers={"Authorization": self.get_credentials()}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 537, in __await_impl__
    transport, protocol = await self._create_connection()
  File "uvloop/loop.pyx", line 2019, in create_connection
  File "uvloop/loop.pyx", line 2014, in uvloop.loop.Loop.create_connection
  File "uvloop/sslproto.pyx", line 515, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 497, in uvloop.loop.SSLProtocol._do_handshake
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
```
电脑是Mac，是需要一个证书吗？

**Comment by abersheeran** [comment]
远端服务器必须需要支持 wss 访问。否则无法保证 websocket 传递的内容安全。

**Comment by abersheeran** [comment]
在朋友的 MacOS 上复现了此问题，是 Python3 的 SSL 模块在 MacOS 上的 BUG。
解决方案参考 StackOverflow：https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
